<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup><Compile Include="Build/Program.fs" /></ItemGroup>
  <ItemGroup><PackageReference Include="Partas.Build" Version="0.8.1" /><PackageReference Include="Partas.Build.Baked" Version="0.3.0" /></ItemGroup>
</Project>
